permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: SnailS
  email: godhuyang@gmail.com
  link: http://snails.github.io
  weibo: 
  github: http://github.com/snails
  music: 
  linkedin: 

# 站点信息
title: Snail's Blog
description: My personal blog
url: http://snails.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-31475638-1
  url: snails.github.io

# disqus 设置
disqus:
  shortname: davidwei

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Ruby
  - Database

# 中文本地化
locals:
  tags:  标签
  about:  关于
  newest: Newest
  archive: 归档
